FROM node:16.15.0

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install phantomjs-prebuilt@2.1.16 -ignore-scripts
RUN npm install
COPY . .

CMD ENV=qa npm run UI-REMOTE --conf=wdio_confs/wdio.grid.conf.js -- --tags=@hybrid


